export const TweetTypes = {
    SET_TWEET_MESSAGE: 'SET_TWEET_MESSAGE',
    SEARCH_TWEET: 'SEARCH_TWEET',
    SEND_TWEET: 'SEND_TWEET',
    SET_TWEET_LIKES: 'SET_TWEET_LIKES',
    SET_TWEET_RETWEETS: 'SET_TWEET_RETWEETS',
    SEARCH_USER: 'SEARCH_USER',
    HOME:'HOME',
}